#!/bin/bash

# 1: command-line parameters
#    $0, $1, $2,...$9, ${10}, ${11}

# 2: last parameter
#    ${!#}
#    or
#    args=$#		# numbers of parameter
#    lastarg=${!args}
echo "last parameter: ${!#}"
args=$#
lastarg=${!args}
echo "last parameter: $lastarg"


# 3: $* or $@: all the parameters
echo "all parameter: $*"
echo "all parameter: $@"

