#!/bin/bash

# value compute using let

# M1:
# using quotion -- security coding
#
echo M1: security coding

let "var1=2*(3+4)"
echo "var1=$var1"

# plus 1
let "var1++"
echo "var1=$var1"

# plus 1
let "var1=$var1+1"
echo "var1=$var1"

# plus 1
let "var1+=1"
echo "var1=$var1"


echo ----------
echo M2:

# M2
# whitout quotion
#
let var2=2*\(3+4\)
echo "var2=$var2"

# plus 1
let var2++
echo "var2=$var2"

# plus 1
let var2=$var2+1
echo "var2=$var2"

# plus 1
let var2+=1
echo "var2=$var2"
