#!/bin/bash

# 1: full quoting(single quote)
#	'STRING' preserves all special characters within STRING
# TODO: sample?

# ' must in pair

# every special character gets interpreted literally(the same character)
# except ' itself
echo "Why can't I write 's between single quotes"
echo
# The roundabout method.
echo 'Why can'\''t I write '"'"'s between single quotes'
#    |-------|  |----------| ↑ |-----------------------|
#                          " ' "
# Three single-quoted strings, with escaped and quoted single quotes between.
# This example courtesy of Stéphane Chazelas.
