#!/bin/bash

# backslash

# 1: quoting, same as `` or weekened ""
# the escape(\) preceding character tells the shell to interpret that character literally
echo  use backslash: \X

echo use double quotion: "X"

echo use single quotion: 'X'

# 2: special meanings of certain escaped characters

#	\n	:	newline
#	\r	:	return
#	\t	:	tab
#	\v	:	vertical tab
#	\b	:	backspace
#	\a	:	alert(beep or flash)
#	\0xx	:	translate to the octal ASCII equivalent of 0nn,
#			where nn is a string of digits




